// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/telemetry.proto

package telemetrypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineControl_Ignite_FullMethodName = "/launchpad.telemetry.v1.EngineControl/Ignite"
	EngineControl_Abort_FullMethodName  = "/launchpad.telemetry.v1.EngineControl/Abort"
	EngineControl_Status_FullMethodName = "/launchpad.telemetry.v1.EngineControl/Status"
)

// EngineControlClient is the client API for EngineControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EngineControl is the gRPC service exposed by the engine service.
// mission-control calls it to schedule a launch and to stream live
// engine telemetry back for the duration of a flight.
type EngineControlClient interface {
	// Ignite starts a simulated engine burn for a given launch and
	// streams telemetry frames back until the burn completes or fails.
	// This is the primary server-streaming RPC exercised by load tests.
	Ignite(ctx context.Context, in *IgniteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetryFrame], error)
	// Abort requests an immediate, unary shutdown of a running burn.
	// Useful for exercising short-lived unary gRPC calls alongside the
	// long-lived stream above.
	Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*AbortResponse, error)
	// Status is a cheap unary health/state check, useful as a
	// high-QPS, low-payload gRPC target distinct from Ignite's stream.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type engineControlClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineControlClient(cc grpc.ClientConnInterface) EngineControlClient {
	return &engineControlClient{cc}
}

func (c *engineControlClient) Ignite(ctx context.Context, in *IgniteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetryFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineControl_ServiceDesc.Streams[0], EngineControl_Ignite_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IgniteRequest, TelemetryFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineControl_IgniteClient = grpc.ServerStreamingClient[TelemetryFrame]

func (c *engineControlClient) Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*AbortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortResponse)
	err := c.cc.Invoke(ctx, EngineControl_Abort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineControlClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, EngineControl_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineControlServer is the server API for EngineControl service.
// All implementations must embed UnimplementedEngineControlServer
// for forward compatibility.
//
// EngineControl is the gRPC service exposed by the engine service.
// mission-control calls it to schedule a launch and to stream live
// engine telemetry back for the duration of a flight.
type EngineControlServer interface {
	// Ignite starts a simulated engine burn for a given launch and
	// streams telemetry frames back until the burn completes or fails.
	// This is the primary server-streaming RPC exercised by load tests.
	Ignite(*IgniteRequest, grpc.ServerStreamingServer[TelemetryFrame]) error
	// Abort requests an immediate, unary shutdown of a running burn.
	// Useful for exercising short-lived unary gRPC calls alongside the
	// long-lived stream above.
	Abort(context.Context, *AbortRequest) (*AbortResponse, error)
	// Status is a cheap unary health/state check, useful as a
	// high-QPS, low-payload gRPC target distinct from Ignite's stream.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedEngineControlServer()
}

// UnimplementedEngineControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineControlServer struct{}

func (UnimplementedEngineControlServer) Ignite(*IgniteRequest, grpc.ServerStreamingServer[TelemetryFrame]) error {
	return status.Error(codes.Unimplemented, "method Ignite not implemented")
}
func (UnimplementedEngineControlServer) Abort(context.Context, *AbortRequest) (*AbortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Abort not implemented")
}
func (UnimplementedEngineControlServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedEngineControlServer) mustEmbedUnimplementedEngineControlServer() {}
func (UnimplementedEngineControlServer) testEmbeddedByValue()                       {}

// UnsafeEngineControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineControlServer will
// result in compilation errors.
type UnsafeEngineControlServer interface {
	mustEmbedUnimplementedEngineControlServer()
}

func RegisterEngineControlServer(s grpc.ServiceRegistrar, srv EngineControlServer) {
	// If the following call panics, it indicates UnimplementedEngineControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineControl_ServiceDesc, srv)
}

func _EngineControl_Ignite_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IgniteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineControlServer).Ignite(m, &grpc.GenericServerStream[IgniteRequest, TelemetryFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineControl_IgniteServer = grpc.ServerStreamingServer[TelemetryFrame]

func _EngineControl_Abort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineControlServer).Abort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineControl_Abort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineControlServer).Abort(ctx, req.(*AbortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineControl_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineControlServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineControl_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineControlServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineControl_ServiceDesc is the grpc.ServiceDesc for EngineControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "launchpad.telemetry.v1.EngineControl",
	HandlerType: (*EngineControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Abort",
			Handler:    _EngineControl_Abort_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _EngineControl_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ignite",
			Handler:       _EngineControl_Ignite_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/telemetry.proto",
}
