// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/telemetry.proto

package telemetrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stage int32

const (
	Stage_STAGE_UNSPECIFIED     Stage = 0
	Stage_STAGE_IGNITION        Stage = 1
	Stage_STAGE_ASCENT          Stage = 2
	Stage_STAGE_SEPARATION      Stage = 3
	Stage_STAGE_ORBIT_INSERTION Stage = 4
	Stage_STAGE_COMPLETE        Stage = 5
	Stage_STAGE_ABORTED         Stage = 6
)

// Enum value maps for Stage.
var (
	Stage_name = map[int32]string{
		0: "STAGE_UNSPECIFIED",
		1: "STAGE_IGNITION",
		2: "STAGE_ASCENT",
		3: "STAGE_SEPARATION",
		4: "STAGE_ORBIT_INSERTION",
		5: "STAGE_COMPLETE",
		6: "STAGE_ABORTED",
	}
	Stage_value = map[string]int32{
		"STAGE_UNSPECIFIED":     0,
		"STAGE_IGNITION":        1,
		"STAGE_ASCENT":          2,
		"STAGE_SEPARATION":      3,
		"STAGE_ORBIT_INSERTION": 4,
		"STAGE_COMPLETE":        5,
		"STAGE_ABORTED":         6,
	}
)

func (x Stage) Enum() *Stage {
	p := new(Stage)
	*p = x
	return p
}

func (x Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_telemetry_proto_enumTypes[0].Descriptor()
}

func (Stage) Type() protoreflect.EnumType {
	return &file_proto_telemetry_proto_enumTypes[0]
}

func (x Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stage.Descriptor instead.
func (Stage) EnumDescriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

type IgniteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LaunchId        string                 `protobuf:"bytes,1,opt,name=launch_id,json=launchId,proto3" json:"launch_id,omitempty"`
	Vehicle         string                 `protobuf:"bytes,2,opt,name=vehicle,proto3" json:"vehicle,omitempty"` // e.g. "vega-c", "vega-e"
	TargetThrustKn  float64                `protobuf:"fixed64,3,opt,name=target_thrust_kn,json=targetThrustKn,proto3" json:"target_thrust_kn,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // simulated burn duration
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IgniteRequest) Reset() {
	*x = IgniteRequest{}
	mi := &file_proto_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IgniteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgniteRequest) ProtoMessage() {}

func (x *IgniteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgniteRequest.ProtoReflect.Descriptor instead.
func (*IgniteRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *IgniteRequest) GetLaunchId() string {
	if x != nil {
		return x.LaunchId
	}
	return ""
}

func (x *IgniteRequest) GetVehicle() string {
	if x != nil {
		return x.Vehicle
	}
	return ""
}

func (x *IgniteRequest) GetTargetThrustKn() float64 {
	if x != nil {
		return x.TargetThrustKn
	}
	return 0
}

func (x *IgniteRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type TelemetryFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaunchId      string                 `protobuf:"bytes,1,opt,name=launch_id,json=launchId,proto3" json:"launch_id,omitempty"`
	TPlusMs       int64                  `protobuf:"varint,2,opt,name=t_plus_ms,json=tPlusMs,proto3" json:"t_plus_ms,omitempty"` // milliseconds since ignition
	AltitudeM     float64                `protobuf:"fixed64,3,opt,name=altitude_m,json=altitudeM,proto3" json:"altitude_m,omitempty"`
	VelocityMps   float64                `protobuf:"fixed64,4,opt,name=velocity_mps,json=velocityMps,proto3" json:"velocity_mps,omitempty"`
	ThrustKn      float64                `protobuf:"fixed64,5,opt,name=thrust_kn,json=thrustKn,proto3" json:"thrust_kn,omitempty"`
	FuelPct       float64                `protobuf:"fixed64,6,opt,name=fuel_pct,json=fuelPct,proto3" json:"fuel_pct,omitempty"`
	Stage         Stage                  `protobuf:"varint,7,opt,name=stage,proto3,enum=launchpad.telemetry.v1.Stage" json:"stage,omitempty"`
	Note          string                 `protobuf:"bytes,8,opt,name=note,proto3" json:"note,omitempty"` // e.g. "MECO", "stage separation"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryFrame) Reset() {
	*x = TelemetryFrame{}
	mi := &file_proto_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryFrame) ProtoMessage() {}

func (x *TelemetryFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryFrame.ProtoReflect.Descriptor instead.
func (*TelemetryFrame) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryFrame) GetLaunchId() string {
	if x != nil {
		return x.LaunchId
	}
	return ""
}

func (x *TelemetryFrame) GetTPlusMs() int64 {
	if x != nil {
		return x.TPlusMs
	}
	return 0
}

func (x *TelemetryFrame) GetAltitudeM() float64 {
	if x != nil {
		return x.AltitudeM
	}
	return 0
}

func (x *TelemetryFrame) GetVelocityMps() float64 {
	if x != nil {
		return x.VelocityMps
	}
	return 0
}

func (x *TelemetryFrame) GetThrustKn() float64 {
	if x != nil {
		return x.ThrustKn
	}
	return 0
}

func (x *TelemetryFrame) GetFuelPct() float64 {
	if x != nil {
		return x.FuelPct
	}
	return 0
}

func (x *TelemetryFrame) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_STAGE_UNSPECIFIED
}

func (x *TelemetryFrame) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type AbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaunchId      string                 `protobuf:"bytes,1,opt,name=launch_id,json=launchId,proto3" json:"launch_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_proto_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *AbortRequest) GetLaunchId() string {
	if x != nil {
		return x.LaunchId
	}
	return ""
}

func (x *AbortRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AbortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortResponse) Reset() {
	*x = AbortResponse{}
	mi := &file_proto_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortResponse) ProtoMessage() {}

func (x *AbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortResponse.ProtoReflect.Descriptor instead.
func (*AbortResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *AbortResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AbortResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveBurns   int32                  `protobuf:"varint,1,opt,name=active_burns,json=activeBurns,proto3" json:"active_burns,omitempty"`
	EngineVersion string                 `protobuf:"bytes,2,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetActiveBurns() int32 {
	if x != nil {
		return x.ActiveBurns
	}
	return 0
}

func (x *StatusResponse) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

var File_proto_telemetry_proto protoreflect.FileDescriptor

const file_proto_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x15proto/telemetry.proto\x12\x16launchpad.telemetry.v1\"\x9b\x01\n" +
	"\rIgniteRequest\x12\x1b\n" +
	"\tlaunch_id\x18\x01 \x01(\tR\blaunchId\x12\x18\n" +
	"\avehicle\x18\x02 \x01(\tR\avehicle\x12(\n" +
	"\x10target_thrust_kn\x18\x03 \x01(\x01R\x0etargetThrustKn\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x05R\x0fdurationSeconds\"\x8c\x02\n" +
	"\x0eTelemetryFrame\x12\x1b\n" +
	"\tlaunch_id\x18\x01 \x01(\tR\blaunchId\x12\x1a\n" +
	"\tt_plus_ms\x18\x02 \x01(\x03R\atPlusMs\x12\x1d\n" +
	"\n" +
	"altitude_m\x18\x03 \x01(\x01R\taltitudeM\x12!\n" +
	"\fvelocity_mps\x18\x04 \x01(\x01R\vvelocityMps\x12\x1b\n" +
	"\tthrust_kn\x18\x05 \x01(\x01R\bthrustKn\x12\x19\n" +
	"\bfuel_pct\x18\x06 \x01(\x01R\afuelPct\x123\n" +
	"\x05stage\x18\a \x01(\x0e2\x1d.launchpad.telemetry.v1.StageR\x05stage\x12\x12\n" +
	"\x04note\x18\b \x01(\tR\x04note\"C\n" +
	"\fAbortRequest\x12\x1b\n" +
	"\tlaunch_id\x18\x01 \x01(\tR\blaunchId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"E\n" +
	"\rAbortResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rStatusRequest\"Z\n" +
	"\x0eStatusResponse\x12!\n" +
	"\factive_burns\x18\x01 \x01(\x05R\vactiveBurns\x12%\n" +
	"\x0eengine_version\x18\x02 \x01(\tR\rengineVersion*\x9c\x01\n" +
	"\x05Stage\x12\x15\n" +
	"\x11STAGE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTAGE_IGNITION\x10\x01\x12\x10\n" +
	"\fSTAGE_ASCENT\x10\x02\x12\x14\n" +
	"\x10STAGE_SEPARATION\x10\x03\x12\x19\n" +
	"\x15STAGE_ORBIT_INSERTION\x10\x04\x12\x12\n" +
	"\x0eSTAGE_COMPLETE\x10\x05\x12\x11\n" +
	"\rSTAGE_ABORTED\x10\x062\x99\x02\n" +
	"\rEngineControl\x12Y\n" +
	"\x06Ignite\x12%.launchpad.telemetry.v1.IgniteRequest\x1a&.launchpad.telemetry.v1.TelemetryFrame0\x01\x12T\n" +
	"\x05Abort\x12$.launchpad.telemetry.v1.AbortRequest\x1a%.launchpad.telemetry.v1.AbortResponse\x12W\n" +
	"\x06Status\x12%.launchpad.telemetry.v1.StatusRequest\x1a&.launchpad.telemetry.v1.StatusResponseB@Z>github.com/umamukkara/launchpad/internal/telemetry/telemetrypbb\x06proto3"

var (
	file_proto_telemetry_proto_rawDescOnce sync.Once
	file_proto_telemetry_proto_rawDescData []byte
)

func file_proto_telemetry_proto_rawDescGZIP() []byte {
	file_proto_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)))
	})
	return file_proto_telemetry_proto_rawDescData
}

var file_proto_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_telemetry_proto_goTypes = []any{
	(Stage)(0),             // 0: launchpad.telemetry.v1.Stage
	(*IgniteRequest)(nil),  // 1: launchpad.telemetry.v1.IgniteRequest
	(*TelemetryFrame)(nil), // 2: launchpad.telemetry.v1.TelemetryFrame
	(*AbortRequest)(nil),   // 3: launchpad.telemetry.v1.AbortRequest
	(*AbortResponse)(nil),  // 4: launchpad.telemetry.v1.AbortResponse
	(*StatusRequest)(nil),  // 5: launchpad.telemetry.v1.StatusRequest
	(*StatusResponse)(nil), // 6: launchpad.telemetry.v1.StatusResponse
}
var file_proto_telemetry_proto_depIdxs = []int32{
	0, // 0: launchpad.telemetry.v1.TelemetryFrame.stage:type_name -> launchpad.telemetry.v1.Stage
	1, // 1: launchpad.telemetry.v1.EngineControl.Ignite:input_type -> launchpad.telemetry.v1.IgniteRequest
	3, // 2: launchpad.telemetry.v1.EngineControl.Abort:input_type -> launchpad.telemetry.v1.AbortRequest
	5, // 3: launchpad.telemetry.v1.EngineControl.Status:input_type -> launchpad.telemetry.v1.StatusRequest
	2, // 4: launchpad.telemetry.v1.EngineControl.Ignite:output_type -> launchpad.telemetry.v1.TelemetryFrame
	4, // 5: launchpad.telemetry.v1.EngineControl.Abort:output_type -> launchpad.telemetry.v1.AbortResponse
	6, // 6: launchpad.telemetry.v1.EngineControl.Status:output_type -> launchpad.telemetry.v1.StatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_telemetry_proto_init() }
func file_proto_telemetry_proto_init() {
	if File_proto_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_telemetry_proto_depIdxs,
		EnumInfos:         file_proto_telemetry_proto_enumTypes,
		MessageInfos:      file_proto_telemetry_proto_msgTypes,
	}.Build()
	File_proto_telemetry_proto = out.File
	file_proto_telemetry_proto_goTypes = nil
	file_proto_telemetry_proto_depIdxs = nil
}
